### ISSUE TITLE
My stats banner not working 

### ISSUE THREAD

**Issue by Pradumnasaraf** [0x7EVEN/0x7EVEN#1]
**"My stats banner"** not working in [README.md](https://github.com/0x7EVEN/0x7EVEN/blob/main/README.md) file

![Screenshot from 2022-02-14 23-07-03](https://user-images.githubusercontent.com/51878265/153916890-11c84d93-0c22-4a13-8036-10afcf91d87f.png)

**Comment by 0x7EVEN** [comment]
Hey let me check this..

**Comment by 0x7EVEN** [comment]
sometimes it fails, maybe some rate limiting or wrong response. but thanks for pointing it out
